openapi: 3.0.3
info:
  contact:
    email: tagtuna@gmail.com
    name: Tagbase Dev Team
    url: https://github.com/tagbase/tagbase-server/issues
  description: tagbse-server provides HTTP endpoints for ingestion of various files
    into the Tagbase SQL database. Input file support includes eTUFF (see [here](https://doi.org/10.6084/m9.figshare.10032848.v4)
    and [here](https://doi.org/10.6084/m9.figshare.10159820.v1)) and [nc-eTAG](https://github.com/oceandatainterop/nc-eTAG/)
    files; a metadata and data interoperability standard for (non-acoustic) electronic
    tagging datasets. The REST API complies with [OpenAPI v3.0.3](https://spec.openapis.org/oas/v3.0.3.html)
    until the tooling for OpenAPI v3.1.0 improves.
  license:
    name: Apache License v2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  termsOfService: TODO
  title: tagbase-server API
  version: v0.4.0
servers:
- description: Local development tagbase-server
  url: https://0.0.0.0:5433/v0.4.0
tags:
- description: Operations relating to the ingestion of data into tagbase-server.
  name: ingest
paths:
  /ingest/etuff:
    get:
      description: GET an eTUFF file from a network accessible location and perform
        an ingest operation.
      operationId: ingest_etuff_get
      parameters:
      - description: Location of a network accessible (file, ftp, http, https) eTUFF
          file e.g. 'file:///usr/src/app/data/eTUFF-sailfish-117259.txt'
        explode: true
        in: query
        name: file
        required: true
        schema:
          maxLength: 100
          minLength: 10
          pattern: ^(?!\s*$).+
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get eTUFF file and execute ingestion
      tags:
      - ingest
      x-openapi-router-controller: tagbase_server.controllers.ingest_controller
    post:
      description: POST an eTUFF file and perform a ingest operation.
      operationId: ingest_etuff_post
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: POST an eTUFF file and perform a ingest operation
      tags:
      - ingest
      x-openapi-router-controller: tagbase_server.controllers.ingest_controller
components:
  requestBodies:
    inline_object:
      content:
        multipart/form-data:
          schema:
            description: The file to be ingested into tagbase-server
            properties:
              file:
                description: The file content
                format: binary
                maxLength: 1000000
                minLength: 1000
                type: string
            type: object
      required: true
  schemas:
    Response200:
      description: HTTP 200 success response
      example:
        code: "200"
        elapsed: 0:00:58.506691
        message: Data file eTUFF-sailfish-117259.txt successfully ingested into Tagbase
          DB.
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        elapsed:
          description: Elapsed time for the operation
          type: string
        message:
          description: A string detailing specifics of an HTTP operation
          example: Data file eTUFF-sailfish-117259.txt successfully ingested into
            Tagbase DB.
          type: string
      title: Response200
      type: object
    Response500:
      description: 500 Internal Server Error
      example:
        code: "200"
        message: Unable to connect to the Tagbase database
        more_info: https://httpwg.org/specs/rfc7231.html#status.500
        trace: 123e4567-e89b-12d3-a456-426614174000
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        message:
          description: A string detailing specifics of an HTTP operation
          example: Data file eTUFF-sailfish-117259.txt successfully ingested into
            Tagbase DB.
          type: string
        more_info:
          description: Additional details (if available) to diagnose the 500 response.
          example: https://httpwg.org/specs/rfc7231.html#status.500
          type: string
        trace:
          description: Trace diagnostic information related to the response
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
      title: Response500
      type: object
