openapi: 3.0.3
info:
  contact:
    email: tagtuna@gmail.com
    name: Tagbase Dev Team
    url: https://github.com/tagbase/tagbase-server/issues
  description: |
    tagbse-server provides HTTP endpoints for ingestion of various files \
    into the Tagbase SQL database. Input file support includes eTUFF (see [here](https://doi.org/10.6084/m9.figshare.10032848.v4) \
    and [here](https://doi.org/10.6084/m9.figshare.10159820.v1)) and [nc-eTAG](https://github.com/oceandatainterop/nc-eTAG/) \
    files; a metadata and data interoperability standard for (non-acoustic) electronic \
    tagging datasets. The REST API complies with [OpenAPI v3.0.3](https://spec.openapis.org/oas/v3.0.3.html) \
    until the tooling for OpenAPI v3.1.0 improves.
  license:
    name: Apache License v2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  termsOfService: TODO
  title: tagbase-server API
  version: v0.5.0
servers:
- description: Local development tagbase-server
  url: https://0.0.0.0:5433/v0.5.0
tags:
- description: Operations relating to the ingestion of data into tagbase-server.
  name: ingest
- description: Operations for querying tags ingested into Tagbase.
  name: tags
paths:
  /ingest:
    get:
      description: Get network accessible file and execute ingestion
      operationId: ingest_get
      parameters:
      - description: Location of a network accessible (file, ftp, http, https)
          file e.g. 'file:///usr/src/app/data/eTUFF-sailfish-117259.txt'
        explode: true
        in: query
        name: file
        required: true
        schema:
          maxLength: 100
          minLength: 10
          pattern: ^(?!\s*$).+
          type: string
        style: form
      - $ref: '#/components/parameters/type'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingest200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get network accessible file and execute ingestion
      tags:
      - ingest
      x-openapi-router-controller: tagbase_server.controllers.ingest_controller
    post:
      description: Post a local file and perform a ingest operation
      operationId: ingest_post
      parameters:
      - $ref: '#/components/parameters/type'
      requestBody:
        content:
          text/plain:
            schema:
              description: text file containing eTUFF data
              format: binary
              maxLength: 1000000
              minLength: 1
              type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingest200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Post a local file and perform a ingest operation
      tags:
      - ingest
      x-codegen-request-body-name: etuff_body
      x-openapi-router-controller: tagbase_server.controllers.ingest_controller
  /tags:
    get:
      description: Get information about all tags
      operationId: list_tags
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get information about all tags
      tags:
      - tags
      x-openapi-router-controller: tagbase_server.controllers.tags_controller
  /tags/{tag_id}:
    get:
      description: Get information about an individual tag
      operationId: get_tag
      parameters:
      - description: submission id for an existing tag
        in: path
        name: tag_id
        required: true
        schema:
          type: number
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag200'
          description: A success message confirming ingestion.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response500'
          description: Internal tagbase-server error. Contact admin detailed in openapi.yaml.
      summary: Get information about an individual tag
      tags:
      - tags
      x-openapi-router-controller: tagbase_server.controllers.tags_controller
components:
  parameters:
    type:
      description: Type of file to be ingested, defaults to 'etuff'
      explode: true
      in: query
      name: type
      required: false
      schema:
        default: etuff
        enum:
          - etuff
          - netcdf
        type: string
      style: form
  schemas:
    Ingest200:
      description: HTTP 200 success response
      example:
        code: "200"
        elapsed: '0:00:58.506691'
        message: Data file eTUFF-sailfish-117259.txt successfully ingested into Tagbase
          DB.
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        elapsed:
          description: Elapsed time for the operation
          type: string
        message:
          description: A string detailing specifics of an HTTP operation
          example: Data file eTUFF-sailfish-117259.txt successfully ingested into
            Tagbase DB.
          type: string
      title: Ingest200
      type: object
    Response500:
      description: 500 Internal Server Error
      example:
        code: "200"
        message: Unable to connect to the Tagbase database
        more_info: https://httpwg.org/specs/rfc7231.html#status.500
        trace: 123e4567-e89b-12d3-a456-426614174000
      properties:
        code:
          description: HTTP status code
          example: "200"
          type: string
        message:
          description: A string detailing specifics of the HTTP 500 response
          example: Data file eTUFF-sailfish-117259.txt successfully ingested into
            Tagbase DB.
          type: string
        more_info:
          description: Additional details (if available) to diagnose the 500 response.
          example: https://httpwg.org/specs/rfc7231.html#status.500
          type: string
        trace:
          description: Trace diagnostic information related to the response
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
      title: Response500
      type: object
    Tag200:
      description: Information for a given tag
      example:
        tag:
        - date_time: '2022-04-01T04:58:21.319061+00:00'
          filename: 'eTUFF-sailfish-117259_2.txt'
          submission_id: 5
          tag_id: 3
          version: '2.0'
        - date_time: '2022-04-01T05:39:46.896088+00:00'
          filename: 'eTUFF-sailfish-117259_2.txt'
          submission_id: 6
          tag_id: 3
          version: '2.0'
      properties:
        tag:
          description: List containing one or more submissions for a given tag
          items:
            type: object
            properties:
              date_time:
                description: Local datetime stamp at the time of eTUFF tag data file ingestion
                example: '2022-04-01T04:58:21.319061+00:00'
                #format: date
                #pattern: '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(([+-]\d\d:\d\d)|Z)?$'
                type: string
              filename:
                description: Full name and extension of the ingested eTUFF tag data file
                example: "eTUFF-sailfish-117259_2.txt"
                type: string
              submission_id:
                description: Unique numeric ID assigned upon submission of a tag eTUFF data file for ingest/importation into Tagbase
                example: 5
                type: integer
              tag_id:
                description: Unique numeric Tag ID associated with the ingested tag eTUFF data file
                example: 3
                type: integer
              version:
                description: Version identifier for the eTUFF tag data file ingested
                example: '2.0'
                type: string
          type: array
      title: Tag200
      type: object
    Tags200:
      description: Response detailing all unique tags available in TagbaseDB
      example:
        count: 2
        tag_ids:
        - 1
        - 3
      properties:
        count:
          description: Total count of unique tags
          example: 2
          type: integer
        tag_ids:
          description: List of unique numeric Tag IDs
          type: array
          items:
            description: Unique numeric Tag ID associated with the ingested tag eTUFF data file
            example:
            - 1
            - 3
            additionalProperties:
              type: integer
      title: Tags200
      type: object
