# coding: utf-8

from __future__ import absolute_import

import re  # noqa: E501
from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from tagbase_server import util
from tagbase_server.models.base_model_ import Model


class IngestAccepted(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, status=None):  # noqa: E501
        """IngestAccepted - a model defined in OpenAPI

        :param id: The id of this IngestAccepted.  # noqa: E501
        :type id: str
        :param status: The status of this IngestAccepted.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {"id": str, "status": str}

        self.attribute_map = {"id": "id", "status": "status"}

        self._id = id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> "IngestAccepted":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IngestAccepted of this IngestAccepted.  # noqa: E501
        :rtype: IngestAccepted
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this IngestAccepted.

        Job id  # noqa: E501

        :return: The id of this IngestAccepted.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this IngestAccepted.

        Job id  # noqa: E501

        :param id: The id of this IngestAccepted.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) > 36:
            raise ValueError(
                "Invalid value for `id`, length must be less than or equal to `36`"
            )  # noqa: E501
        if id is not None and len(id) < 36:
            raise ValueError(
                "Invalid value for `id`, length must be greater than or equal to `36`"
            )  # noqa: E501
        if id is not None and not re.search(
            r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
            id,
        ):  # noqa: E501
            raise ValueError(
                r"Invalid value for `id`, must be a follow pattern or equal to `/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/`"
            )  # noqa: E501

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this IngestAccepted.

        Job status at accept time  # noqa: E501

        :return: The status of this IngestAccepted.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this IngestAccepted.

        Job status at accept time  # noqa: E501

        :param status: The status of this IngestAccepted.
        :type status: str
        """
        allowed_values = ["queued"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}".format(
                    status, allowed_values
                )
            )

        self._status = status
