# coding: utf-8

from __future__ import absolute_import

import re  # noqa: E501
from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from tagbase_server import util
from tagbase_server.models.base_model_ import Model


class IngestJob(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self, id=None, status=None, error=None, files_total=None, files_done=None
    ):  # noqa: E501
        """IngestJob - a model defined in OpenAPI

        :param id: The id of this IngestJob.  # noqa: E501
        :type id: str
        :param status: The status of this IngestJob.  # noqa: E501
        :type status: str
        :param error: The error of this IngestJob.  # noqa: E501
        :type error: str
        :param files_total: The files_total of this IngestJob.  # noqa: E501
        :type files_total: int
        :param files_done: The files_done of this IngestJob.  # noqa: E501
        :type files_done: int
        """
        self.openapi_types = {
            "id": str,
            "status": str,
            "error": str,
            "files_total": int,
            "files_done": int,
        }

        self.attribute_map = {
            "id": "id",
            "status": "status",
            "error": "error",
            "files_total": "files_total",
            "files_done": "files_done",
        }

        self._id = id
        self._status = status
        self._error = error
        self._files_total = files_total
        self._files_done = files_done

    @classmethod
    def from_dict(cls, dikt) -> "IngestJob":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IngestJob of this IngestJob.  # noqa: E501
        :rtype: IngestJob
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this IngestJob.

        Job id  # noqa: E501

        :return: The id of this IngestJob.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this IngestJob.

        Job id  # noqa: E501

        :param id: The id of this IngestJob.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) > 36:
            raise ValueError(
                "Invalid value for `id`, length must be less than or equal to `36`"
            )  # noqa: E501
        if id is not None and len(id) < 36:
            raise ValueError(
                "Invalid value for `id`, length must be greater than or equal to `36`"
            )  # noqa: E501
        if id is not None and not re.search(
            r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
            id,
        ):  # noqa: E501
            raise ValueError(
                r"Invalid value for `id`, must be a follow pattern or equal to `/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/`"
            )  # noqa: E501

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this IngestJob.

        queued, running, succeeded, or failed  # noqa: E501

        :return: The status of this IngestJob.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this IngestJob.

        queued, running, succeeded, or failed  # noqa: E501

        :param status: The status of this IngestJob.
        :type status: str
        """
        allowed_values = ["queued", "running", "succeeded", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}".format(
                    status, allowed_values
                )
            )

        self._status = status

    @property
    def error(self) -> str:
        """Gets the error of this IngestJob.

        Present when the job failed  # noqa: E501

        :return: The error of this IngestJob.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this IngestJob.

        Present when the job failed  # noqa: E501

        :param error: The error of this IngestJob.
        :type error: str
        """
        if error is not None and len(error) > 10000:
            raise ValueError(
                "Invalid value for `error`, length must be less than or equal to `10000`"
            )  # noqa: E501
        if error is not None and len(error) < 1:
            raise ValueError(
                "Invalid value for `error`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if error is not None and not re.search(r"^(?!\s*$).+$", error):  # noqa: E501
            raise ValueError(
                r"Invalid value for `error`, must be a follow pattern or equal to `/^(?!\s*$).+$/`"
            )  # noqa: E501

        self._error = error

    @property
    def files_total(self) -> int:
        """Gets the files_total of this IngestJob.

        Members in the archive, once unpacking has started  # noqa: E501

        :return: The files_total of this IngestJob.
        :rtype: int
        """
        return self._files_total

    @files_total.setter
    def files_total(self, files_total: int):
        """Sets the files_total of this IngestJob.

        Members in the archive, once unpacking has started  # noqa: E501

        :param files_total: The files_total of this IngestJob.
        :type files_total: int
        """
        if files_total is not None and files_total > 2147483647:  # noqa: E501
            raise ValueError(
                "Invalid value for `files_total`, must be a value less than or equal to `2147483647`"
            )  # noqa: E501
        if files_total is not None and files_total < 0:  # noqa: E501
            raise ValueError(
                "Invalid value for `files_total`, must be a value greater than or equal to `0`"
            )  # noqa: E501

        self._files_total = files_total

    @property
    def files_done(self) -> int:
        """Gets the files_done of this IngestJob.

        Members ingested so far  # noqa: E501

        :return: The files_done of this IngestJob.
        :rtype: int
        """
        return self._files_done

    @files_done.setter
    def files_done(self, files_done: int):
        """Sets the files_done of this IngestJob.

        Members ingested so far  # noqa: E501

        :param files_done: The files_done of this IngestJob.
        :type files_done: int
        """
        if files_done is None:
            raise ValueError(
                "Invalid value for `files_done`, must not be `None`"
            )  # noqa: E501
        if files_done is not None and files_done > 2147483647:  # noqa: E501
            raise ValueError(
                "Invalid value for `files_done`, must be a value less than or equal to `2147483647`"
            )  # noqa: E501
        if files_done is not None and files_done < 0:  # noqa: E501
            raise ValueError(
                "Invalid value for `files_done`, must be a value greater than or equal to `0`"
            )  # noqa: E501

        self._files_done = files_done
