# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tagbase_server.models.base_model_ import Model
from tagbase_server import util


class Success(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, fields=None, message=None):  # noqa: E501
        """Success - a model defined in OpenAPI

        :param code: The code of this Success.  # noqa: E501
        :type code: int
        :param fields: The fields of this Success.  # noqa: E501
        :type fields: str
        :param message: The message of this Success.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': int,
            'fields': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'fields': 'fields',
            'message': 'message'
        }

        self._code = code
        self._fields = fields
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Success':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Success of this Success.  # noqa: E501
        :rtype: Success
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this Success.

        abc  # noqa: E501

        :return: The code of this Success.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Success.

        abc  # noqa: E501

        :param code: The code of this Success.
        :type code: int
        """

        self._code = code

    @property
    def fields(self):
        """Gets the fields of this Success.

        null  # noqa: E501

        :return: The fields of this Success.
        :rtype: str
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this Success.

        null  # noqa: E501

        :param fields: The fields of this Success.
        :type fields: str
        """

        self._fields = fields

    @property
    def message(self):
        """Gets the message of this Success.

        A string detailing specifics of the successful operation  # noqa: E501

        :return: The message of this Success.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Success.

        A string detailing specifics of the successful operation  # noqa: E501

        :param message: The message of this Success.
        :type message: str
        """

        self._message = message
