\connect tagbase
INSERT INTO metadata_types (attribute_id, category, attribute_name, "type", description, example, comments, necessity) VALUES
  (1, 'instrument', 'instrument_name', 'string', 'Append an identifer that is unique within your organization. This is essential if a device is recycled.', '16P0100-Refurb2', 'Devices might be reused, so the serial number will be the same. The only way to distinguish is by providing a unique name for the recycled product. ', 'required'),
  (2, 'instrument', 'instrument_type', 'string', 'Type of instrument', 'archival, popup, satellite, acoustic tag, or acoustic receiver', 'Should be restricted to the examples provided.', 'required'),
  (3, 'instrument', 'firmware', 'string', 'Version number of the firmware used to build the device', '', '', 'required'),
  (4, 'instrument', 'manufacturer', 'string', 'Name of manufacturer', 'Wildlife Computers, Microwave Telemetry, Lotek Wireless, Desert Star Systems, CEFAS, StarOddi, Sea Mammal Research Unit, Vemco, Loggerhead Instruments, Biologging Solutions, Little Leonardo, Teleonics etc.', '', 'required'),
  (5, 'instrument', 'model', 'string', 'Model name', 'MiniPAT', '', 'required'),
  (6, 'instrument', 'owner_contact', 'string', 'Contact email/ telephone/ address', '', '', 'required'),
  (7, 'instrument', 'person_owner', 'string', 'Researcher/ organization owning the device', '', 'PI/scientist/organization is used interchargably here. But best to have a first-last name specified here.', 'required'),
  (8, 'instrument', 'serial_number', 'string', 'Serial number', '16P0100', '', 'required'),
  (9, 'instrument', 'date_shipment', 'string', 'Date (yyyy-mm-dd) of receiving the device from manufacturer', '2017-07-11T18:24:23+00:00', 'The device can be fresh off the production line or refurnished with some parts replaced.', 'recommended'),
  (10, 'instrument', 'project', 'string', 'Name or identifer for project/ grant number', '', '', 'recommended'),
  (11, 'instrument', 'ptt', 'string', 'Platform Transmitting Terminal (PTT) number for Argos transmission.', '', '', 'recommended'),
  (12, 'instrument', 'ptt_hex', 'string', 'PTT in hexadecimal', '', '', 'recommended'),
  (13, 'instrument', 'specs', 'string', 'Specification document name/ URL/ file (e.g., in xml)', '', 'Need input from manufacturer. May allow attachment or upload. Or grab it from an online archive.', 'recommended'),
  (14, 'instrument', 'code_map', 'string', 'Placeholder for acoustic tags', '', 'Refer to ATN spec.', 'no'),
  (15, 'instrument', 'ping_code', 'string', 'Placeholder for acoustic tags', '', 'Refer to ATN spec.', 'no'),
  (100, 'programming', 'programming_report', 'string', 'File/ URL to a report listing the details of programming', '', 'Need input from manufacturer. May allow attachment or upload. Or grab it from an online archive.', 'required'),
  (101, 'programming', 'programming_software', 'string', 'Programming software with version number', '', '', 'required'),
  (102, 'programming', 'days_constantdepth', 'string', 'Days at a constant depth before release is initiated ', '1', 'This represents a time lag in days after the tag is  floating/ detached/ sunk before the release procedure will be initiated. ', 'recommended'),
  (103, 'programming', 'days_mission', 'string', 'Programmed mission length in days', '365', '', 'recommended'),
  (104, 'programming', 'minutes_summary', 'string', 'Interval in minutes during when data are summarized for that period', '1440', 'Data are summarized because of Argos transmission constraint.', 'recommended'),
  (105, 'programming', 'person_programmer', 'string', 'Person responsible for the programming', '', '', 'recommended'),
  (106, 'programming', 'seconds_sampling', 'string', 'Sampling rate (seconds) for sensor sampling', '15', 'For basic sensors,  e.g., pressure, temperature, light', 'recommended'),
  (107, 'programming', 'seconds_writingdata', 'string', 'Time interval in seconds when sampled data are written to onboard storage memory', '300', 'This specifies how frequent data will be stored, and subsequently available for download or summarizing.', 'recommended'),
  (108, 'programming', 'seconds_sampling_highfreq', 'string', 'Sampling rate (seconds) for sensor sampling at a higher frequency', '', 'For sensors that sample in Hertz (Hz),  e.g., accelerometer, magnetometer', 'optional'),
  (200, 'attachment', 'attachment_method', 'string', 'Method used to put the tag on/ in the animal', 'tow, glue, suction, anchor, mount, implant, harness, backpack', 'Should be restricted to the examples provided. Tow includes tethered for popup or towed for satellite tags . Glue is using adhensive or epoxy. Mount is using screw, bolt, button, sleeve or backpack. Anchor is equivalent to applying a conventional tag or using a gun (air, spear etc.). Implant implies surgery, ingestion or insertion.', 'required'),
  (201, 'attachment', 'anchor_depth_cm', 'string', 'How deep (centimeter) should the anchor be in the animal?', '8', 'May be used for cetacean tagging.', 'recommended'),
  (202, 'attachment', 'anchor_dimensions_mm', 'string', 'Dimensions (millimeter) as length, width, thichkness or diameter.', '20 L x 14 W', 'Can be used loosely as size: small, medium and large.', 'recommended'),
  (203, 'attachment', 'anchor_material', 'string', 'Material of anchor', 'nylon, urethane, stainless steel, titanium', '', 'recommended'),
  (204, 'attachment', 'anchor_type', 'string', 'Type of anchor', 'Domeier, Wilton, Titanium', '', 'recommended'),
  (205, 'attachment', 'attachment_product', 'string', 'Brand name and/ product for attachment materials used', 'VetBond, Peel Ply, tesa®', 'Brand and product name of suture, stainless steel wire, monofilament, bolt, tape, adhesive, epoxy, suction cup, air gun, speargun, pole, applicator and tip.', 'recommended'),
  (206, 'attachment', 'mount_type', 'string', 'Type of mount', 'Fin, tail, carapacial ridge', '', 'recommended'),
  (207, 'attachment', 'release_method', 'string', 'Method to get a tag detached from the animal/ anchor', 'corrosive burn wire, oxidative/ explosive, galavanizing metal, acoustic release', '', 'recommended'),
  (208, 'attachment', 'tether_assembly', 'string', 'Materials and methods in constructing a tether', 'heat-shrink or silicon tubing', 'Use brand name and/ product when possible.', 'recommended'),
  (209, 'attachment', 'tether_length_cm', 'string', 'End to end length (centimeter) of a tether', '', '', 'recommended'),
  (210, 'attachment', 'tether_material', 'string', 'Tether material for a towed tag', 'stainless steel wire, monofilament', 'Use brand name and/ product when possible.', 'recommended'),
  (211, 'attachment', 'anesthetic_product', 'string', 'Brand name and/ product of anesthesia used during the attachment', 'metomidate, Aqua-S', '', 'optional'),
  (212, 'attachment', 'antifouling_product', 'string', 'Brand name and/ product of antifoluling paint or coating applied ', 'PropSpeed', '', 'optional'),
  (213, 'attachment', 'antiseptic_product', 'string', 'Brand name and/ product of antiseptic or sterilizing agent used during the attachment', 'Iodine, Cicatrin', '', 'optional'),
  (214, 'attachment', 'float_additional', 'string', 'Specify any additional floation used', '', 'Float might be added to archival tags for external use.', 'optional'),
  (215, 'attachment', 'release_forced', 'string', 'If a mechanical release is engaged at depth (too avoid crushing the tag), specify the mechanism and depth at which the release is engaged.', 'Wildlife Computers RD1800', '', 'optional'),
  (300, 'deployment', 'geospatial_lat_start', 'string', 'Latitude (decimal degree) of release/ deployment', '', '', 'required'),
  (301, 'deployment', 'geospatial_lon_start', 'string', 'Longitude (decimal degree) of release/ deployment', '', '', 'required'),
  (302, 'deployment', 'person_tagger_capture', 'string', 'Person responsible for tagging or surgery', '', 'Can be the name of vet, observer, crew, spear fisherman or scientist', 'required'),
  (303, 'deployment', 'time_coverage_start', 'string', 'Local date time (yyyy-mm-dd hh:mm:ss) of release/ deployment', '2017-07-11T18:24:23+00:00', 'http://en.wikipedia.org/wiki/ISO_8601', 'required'),
  (304, 'deployment', 'location_capture', 'string', 'Name or standard identifer of location', '', '', 'recommended'),
  (305, 'deployment', 'method_capture', 'string', 'Type of gear used to catch the animal', 'Longline, purse seine, troll, trawl, rod and reel, handline, set net, trap, gillnet, harpoon, hoop net, anesthesia, tangle net, dip net, vertical line entanglement (commercial fisheries, aquaculture, mooring), dredge, pound net/weir (for turtles)', '', 'recommended'),
  (306, 'deployment', 'baitlure_capture', 'string', 'Bait, chum, lure or decoy used', 'sardine', 'Use brand name and/ product when possible.', 'optional'),
  (307, 'deployment', 'cruise_capture', 'string', 'Name or standard identifer of cruise', '', '', 'optional'),
  (308, 'deployment', 'depth_m_capture', 'string', 'Depth (meters) at which the animal was caught', '', 'Can use estimated depth from hook number on longline', 'optional'),
  (309, 'deployment', 'flag_capture', 'string', 'The vessel’s country of registration', '', '', 'optional'),
  (310, 'deployment', 'hook_capture', 'string', 'Type of hook used', '18/0 circle', 'Use brand name and/ product when possible.', 'optional'),
  (311, 'deployment', 'method_aboard', 'string', 'how was animal put aboard the vessel', 'net, sling, lifted', '', 'optional'),
  (312, 'deployment', 'othertags_capture', 'string', 'List tag IDs for conventional, acoustic, PIT, band or satellite tags for multi-tagged situation, photoID, photo/video footage file names', 'Hallprint PAR007007', '', 'optional'),
  (313, 'deployment', 'person_angler_capture', 'string', 'Person responsible for angling', '', '', 'optional'),
  (314, 'deployment', 'school_capture', 'string', 'Type of school in which the animal was caught', 'Free school, log, anchored FAD, drifting FAD', 'Include FAD number if possible.', 'optional'),
  (315, 'deployment', 'seastate_capture', 'string', 'World Meteorological Organization sea state code (0-9)', '', 'Similar to Douglas Sea Scale ', 'optional'),
  (316, 'deployment', 'set_float_capture', 'string', 'If caught on longline, include set number and float number', '', 'It''s very unlikely to tag turtle, bird/ mammal off longline.', 'optional'),
  (317, 'deployment', 'station_capture', 'string', 'Name or standard identifer of station', '', '', 'optional'),
  (318, 'deployment', 'temp_degC_capture', 'string', 'Air or sea surface temperature (Celcius) when the animal was caught', '', '', 'optional'),
  (319, 'deployment', 'vessel_capture', 'string', 'Name or standard identifer of vessel', '', '', 'optional'),
  (320, 'deployment', 'wind_knots_capture', 'string', 'Wind speed (knots) when the animal was caught', '', '', 'optional'),
  (400, 'animal', 'condition_capture', 'string', 'Description of condition/ injury. Or specify scoring system and a score.', 'good', 'Can be generic: good, bad, gut hooked, eye hooked, bleeding. Scoring system fof fish/ shark:  reflex action mortality predictor (RAMP), Kerstetter''s lab ACES.  Measurement: Bioelectrical Impedance Analysis (BIA) gives phase angle and composition index. Fat: Distell Fatmeter', 'required'),
  (401, 'animal', 'length_capture', 'string', 'Length of the animal', '300', '', 'required'),
  (402, 'animal', 'length_method_capture', 'string', 'Method used to obtain the measurement', 'measured caliper, measured tape,  estimated, calculated', 'Calculated means it''s calculated from length-weight relationships or other conversions.', 'required'),
  (403, 'animal', 'length_type_capture', 'string', 'Type of length measurement', ' Curved fork length, Straight fork length, total length.  for turtle the standard measurements are Curved Carapace Length (CCL), Straight Carapace Length (SCL), Curved Carapace Width (CCW) and Straight Carapace Width (SCW), and researchers occasionally measure girth as well. ', 'May need to compile a list of types and abbreviations', 'required'),
  (404, 'animal', 'length_unit_capture', 'string', 'Unit of length measurement', 'centimeter', 'May need to compile a list of types and abbreviations', 'required'),
  (405, 'animal', 'platform', 'string', 'Common name(s) or FAO code for species name', '', 'Refer to www.itis.gov or FAO species list', 'required'),
  (406, 'animal', 'taxonomic_serial_number', 'string', 'Taxononomic Serial Number (TSN) from Integrated Taxonomic Information System', '', 'https://www.itis.gov', 'required'),
  (500, 'animal', 'condition_recapture', 'string', 'Description of condition/ injury. Or specify scoring system and a score.', '', 'Can be generic: good, bad, gut hooked, eye hooked, bleeding. Scoring system fof fish/ shark:  reflex action mortality predictor (RAMP), Kerstetter''s lab ACES.  Measurement: Bioelectrical Impedance Analysis (BIA) gives phase angle and composition index. Fat: Distell Fatmeter', 'recommended'),
  (501, 'animal', 'fate_recapture', 'string', 'Fate of the animal upon recapture', 'harvested, released, tag and release, missing, unknown; observed/ photo ID', '', 'recommended'),
  (502, 'animal', 'length_method_recapture', 'string', 'Method used to obtain the measurement', 'measured Caliper, measured tape, estimated, calculated', 'Calculated means it''s calculated from length-weight relationships or other conversions', 'recommended'),
  (503, 'animal', 'length_recapture', 'string', 'Length of the animal', '', '', 'recommended'),
  (504, 'animal', 'length_type_recapture', 'string', 'Type of length measurement', 'SFL, CFL, TL, etc…', 'May need to compile a list of types and abbreviations', 'recommended'),
  (505, 'animal', 'length_unit_recapture', 'string', 'Unit of length measurement', '', 'May need to compile a list of types and abbreviations', 'recommended'),
  (407, 'animal', 'lifestage_capture', 'string', 'Life stage of the animal', 'adult, juvenile, subadult, weaner', '', 'recommended'),
  (506, 'animal', 'lifestage_recapture', 'string', 'Life stage of the animal', '', '', 'recommended'),
  (408, 'animal', 'tag_placement', 'string', 'Description of where the tag was placed.', 'second dorsal fin', '', 'recommended'),
  (507, 'animal', 'age_recapture', 'string', 'Age from direct aging methods if available', 'year-of-young, 3 y.o. etc.', 'Can be used to back calculate age of the individual at capture', 'optional'),
  (409, 'animal', 'hours_soaktime_capture', 'string', 'If caught on longline, specify soak time In hours', '', '', 'optional'),
  (508, 'animal', 'hours_soaktime_recapture', 'string', 'If caught on longline, specify soak time In hours', '', '', 'optional'),
  (410, 'animal', 'implant_numsuture', 'string', 'Number of suture used to close the wound', '', 'Internal archival only', 'optional'),
  (411, 'animal', 'minutes_fighttime_capture', 'string', 'If caught on rod and wheel or handline, specify fight time', '', '', 'optional'),
  (509, 'animal', 'minutes_fighttime_recapture', 'string', 'If caught on rod and wheel or handline, specify fight time', '', '', 'optional'),
  (412, 'animal', 'minutes_operation', 'string', 'Time used (minutes) in carrying out the attachment or surgical procedure.', '', '', 'optional'),
  (413, 'animal', 'minutes_revival', 'string', 'If the animal is revived, specify revival time in minutes', '', 'Can be time used in swimming the animal before release', 'optional'),
  (414, 'animal', 'mount_numbolts', 'string', 'Number of bolts used for mounting', '', '', 'optional'),
  (415, 'animal', 'sex', 'string', 'Sex of the animal', 'male, female, unknown', 'Likely only applicable to sharks upon visual confirmation', 'optional'),
  (416, 'animal', 'stock', 'string', 'Stock origin if known', 'East, West, unknown etc.', '', 'optional'),
  (417, 'animal', 'tissue_sample_capture', 'string', 'List other sample types and sample IDs if collected', 'Blood-ID02101', 'Tissue can be any issue: fin clip, blood, scale, biopsy etc.', 'optional'),
  (510, 'animal', 'tissue_sample_recapture', 'string', 'List other sample types and sample IDs if collected', '', 'Tissue can be any issue: fin clip, blood, scale, hard parts, stomach, muscle, biopsy etc.', 'optional'),
  (418, 'animal', 'weight_capture', 'string', 'Weight of the animal', '1200', '', 'optional'),
  (419, 'animal', 'weight_method_capture', 'string', 'Method used to obtain the measurement', 'measured, estimated, calculated', 'Calculated means it''s calculated from length-weight relationships or other conversions', 'optional'),
  (511, 'animal', 'weight_method_recapture', 'string', 'Method used to obtain the measurement', 'measured, estimated, calculated', 'Calculated means it''s calculated from length-weight relationships or other conversions', 'optional'),
  (512, 'animal', 'weight_recapture', 'string', 'Weight of the animal', '', '', 'optional'),
  (420, 'animal', 'weight_type_capture', 'string', 'Type of weight measurement', 'whole', 'May need to compile a list of types and abbreviations: whole, dressed, gilled & gutted', 'optional'),
  (513, 'animal', 'weight_type_recapture', 'string', 'Type of weight measurement', '', 'May need to compile a list of types and abbreviations: whole, dressed, gilled & gutted', 'optional'),
  (421, 'animal', 'weight_unit_capture', 'string', 'Unit of weight measurement', 'pound', '', 'optional'),
  (514, 'animal', 'weight_unit_recapture', 'string', 'Unit of weight measurement', '', '', 'optional'),
  (600, 'end_of_mission', 'time_coverage_end', 'string', 'End date time (yyyy-mm-dd hh:mm:ss) or date range (BETWEEN yyyy-mm-dd AND yyyy-mm-dd) if estimated/ guessed.', '2017-07-11T18:24:23+00:00', 'http://en.wikipedia.org/wiki/ISO_8601', 'required'),
  (601, 'end_of_mission', 'end_details', 'string', 'TODO', 'GPS, Argos, estimated, calculated, modeled, recovered on animal, floater at sea, animal died and sank, recovered on land, recovered by fishing fleet, recovered in port, transfer in transshipment, found in well number X, recovered in processing plant', '', 'required'),
  (602, 'end_of_mission', 'end_type', 'string', 'Description of how the end point is derived for the device.', 'first reported, recaptured, last transmission, recovered', '', 'required'),
  (603, 'end_of_mission', 'geospatial_lat_end', 'string', 'End latitude', '', '', 'required'),
  (604, 'end_of_mission', 'geospatial_lon_end', 'string', 'End longitude', '', '', 'required'),
  (605, 'end_of_mission', 'locationclass_end', 'string', 'Argos location class for popup location or satellite transmission', '', '', 'recommended'),
  (606, 'end_of_mission', 'datetime_death', 'string', 'If mortality occurs before end datetime, specify date time (yyyy-mm-dd hh:mm:ss)', '2017-07-11T18:24:23+00:00', 'http://en.wikipedia.org/wiki/ISO_8601', 'optional'),
  (700, 'recovery', 'location_recapture', 'string', 'Name or standard identifer of location', '', '', 'recommended'),
  (701, 'recovery', 'method_recapture', 'string', 'Type of gear used to catch the animal', 'Longline, purse seine, troll, trawl, rod and reel, handline, set net, trap, gillnet, harpoon, hoop net, anesthesia, tangle net, dip net, vertical line entanglement (commercial fisheries, aquaculture, mooring), dredge, pound net/weir (for turtles)', '', 'recommended'),
  (702, 'recovery', 'person_recapture', 'string', 'Person responsible for the recapture', '', 'Name of angler, observer, scientist, fisher, beach comber etc.', 'recommended'),
  (703, 'recovery', 'baitlure_recapture', 'string', 'Bait, chum, lure or decoy used', '', 'Use brand name and/ product when possible', 'optional'),
  (704, 'recovery', 'cruise_recapture', 'string', 'Name or standard identifer of cruise', '', '', 'optional'),
  (705, 'recovery', 'depth_m_recapture', 'string', 'Depth (meters) at which the animal was caught', '', 'Can use estimated depth from hook number on longline', 'optional'),
  (706, 'recovery', 'flag_capture', 'string', 'The vessel’s country of registration', '', '', 'optional'),
  (707, 'recovery', 'hook_recapture', 'string', 'Type of hook used', '', 'Use brand name and/ product when possible.', 'optional'),
  (708, 'recovery', 'person_tagger_recapture', 'string', 'Person responsible for tag-and-release', '', 'Very unlikely to re-tag turtle or mammal', 'optional'),
  (709, 'recovery', 'retagged_recapture', 'string', 'List tag IDs for conventional, acoustic, PIT, band or satellite tags for multi-tagged situation, photoID, photo/video footage file names', '', '', 'optional'),
  (710, 'recovery', 'school_recapture', 'string', 'Type of school in which the animal was caught', 'Free school, log, anchored FAD, drifting FAD', 'Include FAD number if possible', 'optional'),
  (711, 'recovery', 'seastate_recapture', 'string', 'World Meteorological Organization sea state code (0-9)', '', 'Similar to Douglas Sea Scale ', 'optional'),
  (712, 'recovery', 'set_float_recapture', 'string', 'If caught on longline, include set number and float number', '', '', 'optional'),
  (713, 'recovery', 'station_recapture', 'string', 'Name or standard identifer of station', '', '', 'optional'),
  (714, 'recovery', 'temp_degC_recapture', 'string', 'Air or sea surface temperature (Celcius) when the animal was caught', '', '', 'optional'),
  (715, 'recovery', 'vessel_recapture', 'string', 'Name or standard identifer of vessel', '', '', 'optional'),
  (716, 'recovery', 'wind_knots_recapture', 'string', 'Wind speed (knots) when the animal was caught', '', '', 'optional'),
  (1000, 'waypoints', 'waypoints_source', 'string', 'State the source for waypoints', 'Argos, GPS, acoustic detections, manufacturer, modeled', E'Waypoints are \"points\" along the trajectory of the tagged animal between the start and end dates.', 'required'),
  (1001, 'waypoints', 'geolocation_parameters', 'string', 'List of Geocorrection Parameters and associated values implemented. Comma seperated list in format ''parameter1:value'', ''parameter2:value'',..', 'eg. ''diffusion_coefficien:0.3'', ''satellite_sst'': https://podaac.jpl.nasa.gov/dataset/NCDC-L4LRblend-GLOB-AVHRR_OI'', ...', 'Assuming only 1 set of waypoints per tag data file.', 'recommended'),
  (1002, 'waypoints', 'interpolation_method', 'string', 'None if no interpolation. Otherwise, specify method/ software used.', 'None, crawl, Bézier curves, Hermite splines and cubic splines', '', 'recommended'),
  (1003, 'waypoints', 'interpolation_time', 'string', 'Specify the time interval for interpolation', '0, 1 hour, gap filling', 'Use 0 for no interpolation or gap filling for data points without any coordinates.', 'recommended'),
  (1004, 'waypoints', 'waypoints_method', 'string', E'If \"waypoints_source\" = \"modeled\", specify the method used to estimate the positions. Include citation/ reference/ url if available', 'kftrack, ukfsst, trackit, tripEstimation, SSM, GPE3, Track & Loc, GeoLight, BASTrack, IKNOS', '', 'recommended'),
  (1005, 'waypoints', 'waypoints_software', 'string', 'Software packages used with version number', '', '', 'recommended'),
  (1006, 'waypoints', 'geolocation_output', 'string', 'URL/URI to any relevant geocorrection output file(s) produced', 'eg. ftp://myserver/myfiles.zip', '', 'optional'),
  (1100, 'ancillary_positions', 'ancillary_position_source', 'string', 'List available source(s) for other known position(s)', 'Acoustic detections', 'If an animal is tagged and then released again, this can be included here as well', 'optional'),
  (1101, 'ancillary_positions', 'ancillary_position_instrumentid', 'string', 'List chronologically the instruments collecting the ancillary position(s)', 'receiverID1003, receiverID1008, receiverID1121', '', 'optional'),
  (1102, 'ancillary_positions', 'datetime_ancillary_position', 'string', 'List chronologically the datetime (yyyy-mm-dd hh:mm:ss) for ancillary position(s)', '2016-01-04 22:32:21, 2016-02-01 02:41:11, 2016-03-29 09:15:31', 'http://en.wikipedia.org/wiki/ISO_8601', 'optional'),
  (1103, 'ancillary_positions', 'ancillary_position_lon', 'string', 'List chronologically the longitude for ancillary position(s)', '-153.42,-152.42,-152.49', '', 'optional'),
  (1104, 'ancillary_positions', 'ancillary_position_lat', 'string', 'List chronologically the latitude for ancillary position(s)', '42.131,41.135,42.422', '', 'optional'),
  (1105, 'ancillary_positions', 'ancillary_position_quality', 'string', 'List chronologically the quality (location class/ accuracy/ range etc.) for ancillary position(s). Can be qualitative.', 'LC0,LC1,LCA', 'Can be Argos location class or general descriptions', 'optional'),
  (1200, 'quality', 'found_problem', 'string', 'Is there any problem found in this dataset? One of 3 responses: yes, no, unexamined.', 'yes', '', 'required'),
  (1201, 'quality', 'person_qc', 'string', 'Person responsible for quality control', '', '', 'required'),
  (1202, 'quality', 'problem_affecteddates', 'string', 'Date range (BETWEEN yyyy-mm-dd AND yyyy-mm-dd) in which data quality is in doubt', '', '', 'recommended'),
  (1203, 'quality', 'problem_details', 'string', 'Provide details for the problem(s)', 'Daily drift after sunset by 1.5 degC', '', 'recommended'),
  (1204, 'quality', 'problem_numof', 'string', 'Number of problems found', '1', 'Hard to cover all problems here, e.g., date of post-release mortality/ predation, broken light stalk, broken hardware, tag failure modes', 'recommended'),
  (1205, 'quality', 'problem_summary', 'string', 'List short description(s) for the problem(s)', 'Temperature sensor drift', '', 'recommended'),
  (1206, 'quality', 'calibration_file', 'string', ' Files/ URLs used for calibration of sensors', '', '', 'optional');
