FROM nginx:1.29-bookworm@sha256:8adbdcb969e2676478ee2c7ad333956f0c8e0e4c5a7463f4611d7a2e7a7ff5dc

ARG NGINX_PASS
ARG NGINX_USER

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install --no-install-recommends -y apache2-utils && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN htpasswd -bc /etc/nginx/.htpasswd ${NGINX_USER} ${NGINX_PASS}