name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: psf/black@stable
#       with:
#         #options: "--check --verbose"
#         #src: "."
#         #version: "22.1.0"
