name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: psf/black@stable
#       with:
#         #options: "--check --verbose"
#         #src: "."
#         #version: "22.1.0"
