name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: psf/black@stable
#       with:
#         #options: "--check --verbose"
#         #src: "."
#         #version: "22.1.0"
