name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: psf/black@stable
#       with:
#         #options: "--check --verbose"
#         #src: "."
#         #version: "22.1.0"
